# Generated by Django 5.0.2 on 2024-02-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=11)),
                ('brief_title', models.CharField()),
                ('official_title', models.CharField()),
                ('organization_name', models.CharField()),
                ('organization_type', models.CharField(choices=[('NIH', 'Nih'), ('FED', 'Fed'), ('Other Gov', 'Other Gov'), ('Indiv', 'Indiv'), ('Industry', 'Industry'), ('Network', 'Network'), ('Ambiguous', 'Ambig'), ('Other', 'Other'), ('Unknown', 'Unknown')])),
                ('record_verification_date', models.DateField()),
                ('overall_status', models.CharField(choices=[('Active, not recruiting', 'Active Not Recruiting'), ('Completed', 'Completed'), ('Enrolling by invitation', 'Enrolling By Invitation'), ('Not yet recruiting', 'Not Yet Recruiting'), ('Recruiting', 'Recruiting'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Withdrawn', 'Withdrawn'), ('Available', 'Available'), ('No longer available', 'No Longer Available'), ('Temporarily not available', 'Temporarily Not Available'), ('Approved for marketing', 'Approved For Marketing'), ('Withheld', 'Withheld'), ('Unknown status', 'Unknown')])),
                ('start_date', models.DateField()),
                ('date_posted', models.DateField()),
                ('responsible_party', models.CharField(choices=[('Sponsor', 'Sponsor'), ('Principal Investigator', 'Principal Investigator'), ('Sponsor-Investigator', 'Sponsor Investigator')])),
                ('eligibility_criteria', models.TextField()),
                ('eligible_sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('All', 'All')])),
                ('min_age', models.CharField()),
                ('max_age', models.CharField()),
                ('study_population', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials', models.ManyToManyField(to='trials.clinicaltrial')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials', models.ManyToManyField(to='trials.clinicaltrial')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active, not recruiting', 'Active Not Recruiting'), ('Completed', 'Completed'), ('Enrolling by invitation', 'Enrolling By Invitation'), ('Not yet recruiting', 'Not Yet Recruiting'), ('Recruiting', 'Recruiting'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Withdrawn', 'Withdrawn'), ('Available', 'Available'), ('No longer available', 'No Longer Available'), ('Temporarily not available', 'Temporarily Not Available'), ('Approved for marketing', 'Approved For Marketing'), ('Withheld', 'Withheld'), ('Unknown status', 'Unknown')])),
                ('trials', models.ManyToManyField(to='trials.clinicaltrial')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials', models.ManyToManyField(to='trials.clinicaltrial')),
            ],
        ),
    ]
